// Civic Index design note: this data layer keeps country context explicit, portable, and easy to replace with a real API later.

export type CountryProfile = {
  code: string;
  name: string;
  region: string;
  language: string;
  cities: string[];
  regions: string[];
  streets: string[];
  postalPattern: string;
  trendIdeas: Record<string, string[]>;
};

export const countryProfiles: CountryProfile[] = [
  {
    code: "US",
    name: "United States",
    region: "North America",
    language: "English",
    cities: ["New York", "Los Angeles", "Chicago", "Austin", "Seattle", "Boston"],
    regions: ["NY", "CA", "IL", "TX", "WA", "MA"],
    streets: ["Maple", "Cedar", "Franklin", "Sunset", "Market", "Willow"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["AI productivity tools", "summer travel deals", "local weather alerts", "small business grants", "college football schedule"],
      Technology: ["open source AI", "smart home setup", "developer tools", "cybersecurity basics", "electric vehicle charging"],
      Business: ["startup funding", "remote work policy", "small business taxes", "creator economy", "retail trends"],
      Sports: ["basketball playoffs", "marathon training", "baseball standings", "golf tournament", "football tickets"],
      Entertainment: ["new streaming releases", "concert tickets", "podcast recommendations", "movie showtimes", "festival lineup"],
      News: ["local election guide", "storm updates", "market news", "public transit changes", "city council agenda"],
      Shopping: ["back to school deals", "best running shoes", "home office furniture", "farmers market", "laptop comparison"],
      Travel: ["national park itinerary", "weekend road trip", "best city pass", "airport parking", "budget hotels"],
      Health: ["sleep routine", "community clinic", "healthy meal prep", "mental health resources", "walking groups"],
      Education: ["online certificate programs", "library classes", "scholarship search", "coding bootcamp", "adult learning"],
    },
  },
  {
    code: "GB",
    name: "United Kingdom",
    region: "Europe",
    language: "English",
    cities: ["London", "Manchester", "Bristol", "Edinburgh", "Leeds", "Birmingham"],
    regions: ["Greater London", "Greater Manchester", "Bristol", "Scotland", "West Yorkshire", "West Midlands"],
    streets: ["High", "Church", "King", "Queen", "Victoria", "Mill"],
    postalPattern: "A# #AA",
    trendIdeas: {
      All: ["train timetable updates", "energy bill support", "festival tickets", "local council services", "summer bank holiday plans"],
      Technology: ["AI skills course", "privacy settings", "smart meter guide", "coding events", "cloud certifications"],
      Business: ["small business rates", "freelance tax guide", "startup accelerators", "retail footfall", "office trends"],
      Sports: ["Premier League fixtures", "cricket scores", "tennis tournament", "cycling routes", "football transfer news"],
      Entertainment: ["West End shows", "new BBC series", "music festival dates", "bookshop events", "cinema listings"],
      News: ["local election results", "rail service updates", "weather warning", "public consultation", "NHS update"],
      Shopping: ["vintage markets", "best rain jacket", "home improvement", "independent shops", "student discounts"],
      Travel: ["Lake District weekend", "railcard guide", "London museum pass", "coastal walks", "budget accommodation"],
      Health: ["NHS services", "running clubs", "healthy lunch ideas", "mental health support", "community pharmacy"],
      Education: ["adult education classes", "university open day", "apprenticeships", "library workshops", "online learning"],
    },
  },
  {
    code: "CA",
    name: "Canada",
    region: "North America",
    language: "English",
    cities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Halifax"],
    regions: ["Ontario", "British Columbia", "Quebec", "Alberta", "Ontario", "Nova Scotia"],
    streets: ["King", "Main", "Queen", "Granville", "Lakeview", "Maple"],
    postalPattern: "A#A #A#",
    trendIdeas: {
      All: ["housing rebate guide", "summer road trips", "local wildfire alerts", "public library events", "festival schedule"],
      Technology: ["AI courses Canada", "home internet plans", "data privacy guide", "coding meetup", "electric vehicles"],
      Business: ["small business grants", "startup programs", "remote work policy", "market outlook", "entrepreneur resources"],
      Sports: ["hockey schedule", "basketball tickets", "ski conditions", "soccer league", "marathon events"],
      Entertainment: ["film festival lineup", "concert calendar", "streaming releases", "museum exhibitions", "theatre tickets"],
      News: ["weather alert", "transit service notice", "provincial budget", "community update", "wildfire map"],
      Shopping: ["winter gear deals", "local makers market", "home office setup", "best hiking shoes", "farmers market"],
      Travel: ["Rockies itinerary", "city pass Toronto", "Quebec weekend", "national park reservations", "budget road trip"],
      Health: ["walk-in clinic", "wellness classes", "healthy recipes", "community health", "sleep advice"],
      Education: ["college programs", "library courses", "scholarships Canada", "online diplomas", "career training"],
    },
  },
  {
    code: "AU",
    name: "Australia",
    region: "Oceania",
    language: "English",
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"],
    regions: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "ACT"],
    streets: ["George", "King", "Collins", "Elizabeth", "Crown", "Pacific"],
    postalPattern: "####",
    trendIdeas: {
      All: ["school holiday ideas", "public transport updates", "beach weather", "local events", "cost of living guide"],
      Technology: ["AI training Australia", "home solar guide", "cyber safety", "startup events", "coding courses"],
      Business: ["small business support", "freelance rates", "business grants", "retail outlook", "workspace guide"],
      Sports: ["AFL fixtures", "cricket results", "surf conditions", "running events", "rugby tickets"],
      Entertainment: ["music festival guide", "cinema listings", "gallery opening", "live theatre", "streaming picks"],
      News: ["bushfire update", "weather warnings", "transport alert", "local council", "community news"],
      Shopping: ["summer wardrobe", "market guide", "camping gear", "home decor", "local brands"],
      Travel: ["Great Ocean Road", "city weekend itinerary", "reef tours", "national park guide", "budget stays"],
      Health: ["bulk billing clinic", "fitness classes", "healthy meal prep", "wellbeing resources", "walking tracks"],
      Education: ["TAFE courses", "university open day", "online certificates", "library events", "career change"],
    },
  },
  {
    code: "FR",
    name: "France",
    region: "Europe",
    language: "French",
    cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Bordeaux", "Nantes"],
    regions: ["Île-de-France", "Auvergne-Rhône-Alpes", "Provence-Alpes-Côte d’Azur", "Occitanie", "Nouvelle-Aquitaine", "Pays de la Loire"],
    streets: ["de la République", "Victor Hugo", "Jean Jaurès", "du Général de Gaulle", "des Lilas", "du Port"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["horaires de train", "agenda culturel", "aides rénovation", "marchés locaux", "idées week-end"],
      Technology: ["formation IA", "outils no-code", "cybersécurité", "réparation smartphone", "mobilité électrique"],
      Business: ["aides entreprises", "création micro-entreprise", "télétravail", "commerce local", "étude de marché"],
      Sports: ["calendrier football", "course à pied", "résultats rugby", "randonnées", "billets tennis"],
      Entertainment: ["sorties cinéma", "expositions", "concerts", "festivals", "spectacles"],
      News: ["actualités municipales", "alerte météo", "travaux transport", "démarches publiques", "info régionale"],
      Shopping: ["marché de producteurs", "soldes maison", "librairie indépendante", "mobilier bureau", "mode responsable"],
      Travel: ["itinéraire Bretagne", "pass musées Paris", "week-end en Provence", "hébergement abordable", "visite châteaux"],
      Health: ["médecin de garde", "cours de yoga", "mutuelle santé", "recettes équilibrées", "centre de santé"],
      Education: ["formation professionnelle", "cours du soir", "bourses étudiantes", "bibliothèque ateliers", "formation en ligne"],
    },
  },
  {
    code: "DE",
    name: "Germany",
    region: "Europe",
    language: "German",
    cities: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Leipzig"],
    regions: ["Berlin", "Bavaria", "Hamburg", "North Rhine-Westphalia", "Hesse", "Saxony"],
    streets: ["Haupt", "Bahnhof", "Goethe", "Schiller", "Linden", "Markt"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["Bahn Fahrplan", "Wochenendtipps", "Energieberatung", "Stadtfest Termine", "Wetterwarnung"],
      Technology: ["KI Weiterbildung", "Datenschutz Tipps", "Smart Home", "Programmierkurse", "E-Mobilität"],
      Business: ["Förderprogramme", "Gründungstipps", "Arbeitsmarkt", "Einzelhandel Trends", "Coworking"],
      Sports: ["Bundesliga Spielplan", "Laufveranstaltungen", "Radsport Termine", "Tennis Turnier", "Fitnesskurse"],
      Entertainment: ["Kino Programm", "Konzertkalender", "Museumsnacht", "Theater Tickets", "Buchmesse"],
      News: ["Stadt Nachrichten", "Verkehrsmeldung", "Unwetterwarnung", "Bürgerbeteiligung", "Energie News"],
      Shopping: ["Wochenmarkt", "Secondhand Läden", "Wanderausrüstung", "Büromöbel", "regionale Produkte"],
      Travel: ["Berlin Museumsinsel", "Bayern Wochenendtrip", "Wanderwege", "Bahnreisen", "günstige Hotels"],
      Health: ["Apotheken Notdienst", "Gesundheitszentrum", "Laufgruppe", "Ernährungsberatung", "Pflegeangebote"],
      Education: ["Volkshochschule", "Weiterbildung", "Bibliothekskurse", "Studienberatung", "Online Lernangebote"],
    },
  },
  {
    code: "ES",
    name: "Spain",
    region: "Europe",
    language: "Spanish",
    cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga"],
    regions: ["Comunidad de Madrid", "Catalonia", "Valencian Community", "Andalusia", "Basque Country", "Andalusia"],
    streets: ["Mayor", "Real", "de la Paz", "Gran Vía", "del Mar", "Nueva"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["agenda cultural", "horarios de tren", "planes de verano", "mercados locales", "ayudas vivienda"],
      Technology: ["cursos de IA", "seguridad digital", "domótica", "programación", "movilidad eléctrica"],
      Business: ["ayudas para autónomos", "emprendimiento", "comercio local", "coworking", "tendencias retail"],
      Sports: ["calendario fútbol", "rutas de senderismo", "carreras populares", "pádel", "ciclismo"],
      Entertainment: ["cartelera cine", "conciertos", "festivales", "exposiciones", "teatro"],
      News: ["alerta meteorológica", "transporte público", "noticias municipales", "trámites públicos", "calidad del aire"],
      Shopping: ["mercado de artesanía", "tiendas locales", "ofertas hogar", "librerías", "moda sostenible"],
      Travel: ["escapada de fin de semana", "rutas costeras", "museos Madrid", "alojamiento económico", "parques naturales"],
      Health: ["centro de salud", "farmacia de guardia", "yoga", "recetas saludables", "grupos de caminar"],
      Education: ["formación profesional", "cursos online", "bibliotecas", "becas", "idiomas"],
    },
  },
  {
    code: "IT",
    name: "Italy",
    region: "Europe",
    language: "Italian",
    cities: ["Rome", "Milan", "Naples", "Turin", "Florence", "Bologna"],
    regions: ["Lazio", "Lombardy", "Campania", "Piedmont", "Tuscany", "Emilia-Romagna"],
    streets: ["Roma", "Garibaldi", "Della Libertà", "Dante", "Del Corso", "Marconi"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["orari treni", "eventi culturali", "mercati rionali", "idee weekend", "bonus casa"],
      Technology: ["corso intelligenza artificiale", "privacy online", "smart home", "programmazione", "auto elettriche"],
      Business: ["incentivi imprese", "partita IVA", "coworking", "commercio locale", "analisi mercato"],
      Sports: ["calendario calcio", "corsa cittadina", "ciclismo", "tennis", "palestre"],
      Entertainment: ["programmazione cinema", "mostre", "concerti", "teatro", "festival"],
      News: ["notizie comunali", "allerta meteo", "trasporti", "servizi pubblici", "qualità aria"],
      Shopping: ["mercato locale", "librerie indipendenti", "arredamento", "prodotti artigianali", "abbigliamento"],
      Travel: ["itinerario Toscana", "musei Roma", "weekend Napoli", "borghi da visitare", "hotel economici"],
      Health: ["farmacia di turno", "centro medico", "yoga", "ricette sane", "gruppi cammino"],
      Education: ["formazione professionale", "corsi serali", "biblioteca", "borse di studio", "corsi online"],
    },
  },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe",
    language: "Dutch",
    cities: ["Amsterdam", "Rotterdam", "Utrecht", "The Hague", "Eindhoven", "Groningen"],
    regions: ["North Holland", "South Holland", "Utrecht", "South Holland", "North Brabant", "Groningen"],
    streets: ["Kerk", "Markt", "Koningin", "Nieuwe", "Prins", "Haven"],
    postalPattern: "#### AA",
    trendIdeas: {
      All: ["NS travel updates", "local events", "sustainable living", "market days", "weekend cycling"],
      Technology: ["AI course", "digital privacy", "smart energy", "coding meetup", "e-bike guide"],
      Business: ["startup support", "freelance rules", "retail trends", "shared office", "local grants"],
      Sports: ["cycling routes", "football fixtures", "running events", "rowing clubs", "tennis courts"],
      Entertainment: ["museum exhibitions", "concert calendar", "film listings", "theatre shows", "book events"],
      News: ["municipal news", "weather alert", "transit notice", "public consultation", "air quality"],
      Shopping: ["farmers market", "design shops", "home office", "secondhand stores", "local products"],
      Travel: ["canal cruise", "national park day trip", "museum pass", "bike holiday", "budget hotels"],
      Health: ["huisarts guide", "walking group", "wellness classes", "healthy lunch", "pharmacy"],
      Education: ["Dutch courses", "library workshop", "online certificate", "university events", "career training"],
    },
  },
  {
    code: "BE",
    name: "Belgium",
    region: "Europe",
    language: "French / Dutch",
    cities: ["Brussels", "Antwerp", "Ghent", "Liège", "Bruges", "Leuven"],
    regions: ["Brussels-Capital", "Flanders", "Flanders", "Wallonia", "West Flanders", "Flemish Brabant"],
    streets: ["de la Station", "du Centre", "des Écoles", "de la Paix", "du Marché", "des Fleurs"],
    postalPattern: "####",
    trendIdeas: {
      All: ["train timetable", "local festivals", "public services", "weekend ideas", "market calendar"],
      Technology: ["digital skills", "AI training", "cyber safety", "smart mobility", "coding workshops"],
      Business: ["startup support", "small business grants", "coworking", "local commerce", "market research"],
      Sports: ["cycling events", "football schedule", "running clubs", "tennis", "swimming pools"],
      Entertainment: ["museum nights", "concerts", "cinema listings", "theatre", "book fairs"],
      News: ["city updates", "weather warnings", "transit works", "public consultation", "air quality"],
      Shopping: ["local markets", "design stores", "bookshops", "home office", "artisan products"],
      Travel: ["Bruges day trip", "museum pass", "Ardennes weekend", "city walking route", "budget stays"],
      Health: ["medical centre", "pharmacy rota", "wellness classes", "healthy food", "walking group"],
      Education: ["language courses", "university events", "library workshops", "adult education", "online classes"],
    },
  },
  {
    code: "CH",
    name: "Switzerland",
    region: "Europe",
    language: "French / German / Italian",
    cities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lugano"],
    regions: ["Zürich", "Geneva", "Basel-Stadt", "Bern", "Vaud", "Ticino"],
    streets: ["Bahnhof", "du Lac", "des Alpes", "Central", "de la Gare", "Linden"],
    postalPattern: "####",
    trendIdeas: {
      All: ["SBB timetable", "mountain weather", "local markets", "cultural agenda", "weekend routes"],
      Technology: ["AI Weiterbildung", "digital security", "smart mobility", "coding courses", "energy efficiency"],
      Business: ["startup programmes", "small business advice", "coworking spaces", "market outlook", "innovation grants"],
      Sports: ["hiking routes", "ski conditions", "cycling events", "football fixtures", "running clubs"],
      Entertainment: ["museum exhibitions", "concerts", "cinema programmes", "theatre tickets", "festival guide"],
      News: ["city news", "weather warning", "transport update", "public notice", "air quality"],
      Shopping: ["farmers market", "bookstores", "outdoor gear", "local design", "home office"],
      Travel: ["lake itinerary", "mountain railways", "city pass", "weekend in Ticino", "budget stays"],
      Health: ["medical centre", "pharmacy service", "wellness classes", "healthy recipes", "walking groups"],
      Education: ["continuing education", "language school", "library courses", "university events", "online training"],
    },
  },
  {
    code: "MA",
    name: "Morocco",
    region: "Africa",
    language: "Arabic / French",
    cities: ["Casablanca", "Rabat", "Marrakesh", "Tangier", "Fes", "Agadir"],
    regions: ["Casablanca-Settat", "Rabat-Salé-Kénitra", "Marrakesh-Safi", "Tanger-Tétouan", "Fès-Meknès", "Souss-Massa"],
    streets: ["Mohammed V", "Hassan II", "Al Atlas", "Ibn Sina", "Oued Sebou", "Al Massira"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["horaires de train", "agenda culturel", "marchés locaux", "idées voyage", "services publics"],
      Technology: ["formation digitale", "outils IA", "commerce en ligne", "cybersécurité", "applications utiles"],
      Business: ["création entreprise", "aides PME", "commerce local", "coworking", "tendances tourisme"],
      Sports: ["calendrier football", "randonnée Atlas", "surf Agadir", "course à pied", "salles de sport"],
      Entertainment: ["festivals", "concerts", "cinéma", "expositions", "événements culturels"],
      News: ["météo locale", "travaux routiers", "actualités ville", "transports", "qualité de l’air"],
      Shopping: ["souks", "marchés artisanaux", "librairies", "mobilier maison", "produits locaux"],
      Travel: ["itinéraire Marrakech", "désert weekend", "médina à visiter", "hôtels abordables", "plages Maroc"],
      Health: ["centre médical", "pharmacie de garde", "nutrition", "cours de yoga", "associations santé"],
      Education: ["formation professionnelle", "cours de langues", "bibliothèque", "bourses", "cours en ligne"],
    },
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Middle East",
    language: "Arabic / English",
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah"],
    regions: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Abu Dhabi", "Ras Al Khaimah"],
    streets: ["Sheikh Zayed", "Al Wasl", "Al Nahda", "Corniche", "Al Reem", "Jumeirah"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["weekend events", "metro timings", "mall offers", "weather update", "public services"],
      Technology: ["AI events", "smart city", "digital government", "coding bootcamp", "cybersecurity"],
      Business: ["business setup", "startup events", "free zone guide", "coworking spaces", "market trends"],
      Sports: ["football fixtures", "padel courts", "running events", "golf courses", "fitness classes"],
      Entertainment: ["concert calendar", "cinema listings", "art exhibitions", "family activities", "theatre shows"],
      News: ["traffic updates", "weather alert", "city news", "transport notice", "community events"],
      Shopping: ["local markets", "home decor", "electronics deals", "bookstores", "artisan shops"],
      Travel: ["desert activities", "museum guide", "beach clubs", "weekend hotels", "city itinerary"],
      Health: ["clinic near me", "pharmacy", "wellness classes", "healthy meal prep", "community health"],
      Education: ["professional courses", "language school", "university events", "online learning", "library workshops"],
    },
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    region: "Middle East",
    language: "Arabic",
    cities: ["Riyadh", "Jeddah", "Dammam", "Medina", "Mecca", "Abha"],
    regions: ["Riyadh", "Makkah", "Eastern Province", "Madinah", "Makkah", "Asir"],
    streets: ["King Fahd", "Prince Sultan", "Al Olaya", "King Abdulaziz", "Al Tahlia", "Al Nakheel"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["local events", "weather update", "public services", "weekend plans", "restaurant guide"],
      Technology: ["AI conference", "smart city", "digital services", "coding courses", "tech startups"],
      Business: ["business setup", "SME support", "investment guide", "coworking", "retail trends"],
      Sports: ["football schedule", "padel courts", "running events", "gym near me", "motorsport"],
      Entertainment: ["concerts", "cinema listings", "art exhibitions", "family events", "festival guide"],
      News: ["traffic news", "city announcements", "weather warning", "transport update", "local agenda"],
      Shopping: ["souq guide", "mall offers", "bookstores", "home furniture", "local brands"],
      Travel: ["heritage sites", "desert tours", "Red Sea itinerary", "city hotels", "mountain trips"],
      Health: ["clinic search", "pharmacy", "wellness centre", "healthy recipes", "walking tracks"],
      Education: ["training courses", "university admissions", "language learning", "online courses", "library events"],
    },
  },
  {
    code: "IN",
    name: "India",
    region: "South Asia",
    language: "English / Hindi",
    cities: ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Pune"],
    regions: ["Maharashtra", "Delhi", "Karnataka", "Telangana", "Tamil Nadu", "Maharashtra"],
    streets: ["Gandhi", "Nehru", "MG", "Station", "Lake View", "Ring Road"],
    postalPattern: "######",
    trendIdeas: {
      All: ["train status", "local events", "government services", "weekend trips", "weather update"],
      Technology: ["AI courses", "developer tools", "digital payments", "cyber safety", "startup events"],
      Business: ["small business loans", "startup funding", "market trends", "coworking", "online business"],
      Sports: ["cricket schedule", "football fixtures", "badminton courts", "running events", "fitness classes"],
      Entertainment: ["movie listings", "music events", "book fairs", "art exhibitions", "theatre shows"],
      News: ["city news", "traffic update", "weather alerts", "public schemes", "transit notice"],
      Shopping: ["local markets", "online deals", "bookstores", "home office", "handicrafts"],
      Travel: ["heritage walk", "hill station trip", "city itinerary", "budget hotels", "beach weekend"],
      Health: ["clinic near me", "pharmacy", "healthy recipes", "yoga classes", "public health"],
      Education: ["exam resources", "online courses", "scholarships", "coding classes", "library events"],
    },
  },
  {
    code: "JP",
    name: "Japan",
    region: "East Asia",
    language: "Japanese",
    cities: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo", "Fukuoka"],
    regions: ["Tokyo", "Osaka", "Kyoto", "Kanagawa", "Hokkaido", "Fukuoka"],
    streets: ["Sakura", "Chuo", "Nishi", "Higashi", "Station", "Midori"],
    postalPattern: "###-####",
    trendIdeas: {
      All: ["train timetable", "seasonal events", "local food guide", "weekend itinerary", "weather forecast"],
      Technology: ["AI learning", "smart home", "coding meetup", "digital tools", "robotics events"],
      Business: ["startup events", "small business guide", "remote work", "local commerce", "coworking spaces"],
      Sports: ["baseball schedule", "marathon events", "football fixtures", "ski conditions", "fitness clubs"],
      Entertainment: ["anime events", "concert calendar", "museum exhibitions", "cinema listings", "theatre"],
      News: ["earthquake information", "city updates", "transport notice", "weather alert", "public services"],
      Shopping: ["stationery stores", "local markets", "bookstores", "electronics deals", "craft shops"],
      Travel: ["temple itinerary", "onsen guide", "city pass", "cherry blossom spots", "budget ryokan"],
      Health: ["clinic search", "pharmacy", "healthy lunch", "yoga studio", "wellness guide"],
      Education: ["language school", "university events", "online courses", "library workshop", "study spaces"],
    },
  },
  {
    code: "BR",
    name: "Brazil",
    region: "South America",
    language: "Portuguese",
    cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Recife", "Curitiba"],
    regions: ["São Paulo", "Rio de Janeiro", "Federal District", "Bahia", "Pernambuco", "Paraná"],
    streets: ["São João", "Paulista", "Brasil", "das Flores", "Central", "da Paz"],
    postalPattern: "#####-###",
    trendIdeas: {
      All: ["transporte público", "eventos locais", "previsão do tempo", "feiras", "ideias para o fim de semana"],
      Technology: ["curso de IA", "segurança digital", "ferramentas no-code", "programação", "startups"],
      Business: ["apoio para pequenas empresas", "empreendedorismo", "coworking", "comércio local", "tendências de mercado"],
      Sports: ["jogos de futebol", "corridas", "academias", "surf", "ciclismo"],
      Entertainment: ["cinema", "shows", "exposições", "teatro", "festivais"],
      News: ["notícias da cidade", "alerta de chuva", "trânsito", "serviços públicos", "qualidade do ar"],
      Shopping: ["feira local", "livrarias", "artesanato", "móveis", "moda sustentável"],
      Travel: ["roteiro Rio", "praias", "viagem de fim de semana", "hotéis econômicos", "parques nacionais"],
      Health: ["clínica", "farmácia", "receitas saudáveis", "yoga", "grupos de caminhada"],
      Education: ["cursos profissionalizantes", "bolsas de estudo", "bibliotecas", "cursos online", "idiomas"],
    },
  },
  {
    code: "MX",
    name: "Mexico",
    region: "North America",
    language: "Spanish",
    cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Mérida", "Oaxaca"],
    regions: ["Mexico City", "Jalisco", "Nuevo León", "Puebla", "Yucatán", "Oaxaca"],
    streets: ["Juárez", "Reforma", "Hidalgo", "Morelos", "Independencia", "Insurgentes"],
    postalPattern: "#####",
    trendIdeas: {
      All: ["agenda cultural", "transporte público", "clima local", "mercados", "planes de fin de semana"],
      Technology: ["cursos de IA", "seguridad digital", "programación", "startups", "herramientas digitales"],
      Business: ["apoyos para pymes", "emprendimiento", "coworking", "comercio local", "tendencias retail"],
      Sports: ["partidos de fútbol", "carreras", "gimnasios", "ciclismo", "canchas de pádel"],
      Entertainment: ["cartelera de cine", "conciertos", "museos", "teatro", "festivales"],
      News: ["noticias locales", "alerta meteorológica", "tráfico", "servicios públicos", "calidad del aire"],
      Shopping: ["mercados artesanales", "librerías", "ofertas para hogar", "productos locales", "moda"],
      Travel: ["ruta por Yucatán", "museos CDMX", "pueblos mágicos", "hoteles económicos", "playas"],
      Health: ["clínica cercana", "farmacia", "comida saludable", "clases de yoga", "centro comunitario"],
      Education: ["cursos técnicos", "becas", "bibliotecas", "aprendizaje online", "idiomas"],
    },
  },
];

export const defaultCountry = countryProfiles.find((country) => country.code === "FR") ?? countryProfiles[0];

export const findCountry = (code: string) => countryProfiles.find((country) => country.code === code) ?? defaultCountry;
